### ISSUE TITLE
Sprint Goal 5 - 04/06 - 4/18/207

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#110]
### CMS integrations
- [ ] Map out plan for IAM in ticket #109   
- [ ] Technical exploration of event platforms aka could this work with our current set up #67 
    - [x] Explore Soapbox Engage #114
    - [ ] SplashThat Deep Dive #115
    - [x] Time.ly Deep Dive #116
- [ ] STRETCH: picking 1 event platform and seeing if we can integrate either front end or admin side or both into the CMS
- [ ] STRETCH: code housekeeping 

### CMS themeing
- [ ] Build out theme of basic page #68 

### Artifacts Update
- [x] System architecture drawing #107 - P1
- [ ] Update copy on wireframes either #20 or #38 
- [ ] Exec Deck #111

### User testing
- [ ] Launch first CoSS wireframe test with usertesting.com #64 

### Programmatic Alignment
- [x] need ticket

NOTE: Arielle is out at onboarding a huge part of this sprint
