### ISSUE TITLE
Sprint 6 - 04/20 - 05/02/2017

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#118]
### CMS integrations
- [ ] passwordless login to CoSS #119
- [ ] Staff LDAP login to CoSS #120
- [ ] Dependency on possible vendors: Picking 1 event platform and seeing if we can integrate either front end or admin side or both into the CMS #67 
- [ ] STRETCH: code housekeeping 
- [ ] STRETCH: Signup form process planning
- [ ] STRETCH: Salesforce Exploration #123

### CMS themeing
- [ ] Build out theme of basic page #68 

### Artifacts Update
- [ ] Metaphor Graphic #122
- [ ] Exec Deck #111

### User testing
- [ ] Launch first CoSS wireframe test with usertesting.com #64 

### Programmatic Alignment
- [ ] Alignment Details doc #121
