### ISSUE TITLE
Sprint 7 goal

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#131]
### CMS integrations
- [ ] Signup form creation and integration with IAM and SF
- [ ] Dependency on possible vendors: Picking 1 event platform and seeing if we can integrate either front end or admin side or both into the CMS #67 
- [ ] STRETCH: code housekeeping 

### CMS themeing
- [ ] Build out theme of basic page #68 
- [ ] Build out several layouts #130 

### User testing
- [ ] Launch first CoSS wireframe test with usertesting.com #64 

### Exec Alignment
- [ ] Project Brief
