### ISSUE TITLE
CoSS Sprint 8 Goal

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#142]
## Extend Functionality
**Theme:** _We are able to launch a Club site with basic navigation_
- [ ] Signup form creation and integration with IAM and SF #156, #157
- [ ] Build out several layouts #130 
- [ ] Create a base template for the project and one base template per app. #140 
- [ ] Allow the creation of multiple landing pages for the same app.
- [ ] Dockerize Project #143 

### Maintenance
- [ ] code housekeeping #136, #133, TBD

### Design
**Theme:** _Have a visually designed clickable prototype for Open Source Clubs_
- [ ] Open Source Clubs: Visual Design #145
- [ ] Apply visual design to the Club Captain flow #146 
- [ ] Apply visual design to the Club Member flow #147
- [ ] Create Clickable Prototype: Visual Design #148 

### Deployment
- [ ] Deploy on ParSys AWS infrastructure (coss.staging.paas.mozilla.community, coss.mozilla.community) #155
