### ISSUE TITLE
Open Source Clubs : Visual Design

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#145]
**Design a UI flow that prototypes the following journeys in a clickable, visually designed prototype:**

- Club Captains: How users start a club
- Club Members: How users join a club

---

**Tasks to start this epic:**
- [x] Re-familiarize with Open Source Clubs user personas, journeys and wireframes.
- [x] Obtain current wireframe files and assets from Kristina, this includes latest direction for Mozilla Open Source Clubs branding/naming.
- [x] Understand status of latest user testing for wireframes, are there any learnings that can be applied to this UI?

**Comment by m-branson** [comment]
A WIP [outline](https://docs.google.com/a/mozilla.com/document/d/1IAtQlUtNU6yA8xJJkl1EyEiEnkXtNPl6QOLE_zzL9Gg/edit?usp=sharing) has been populated to prioritize visual prototype features as “Expected for June 2017 All Hands” vs. “Next Steps”. UX/UI functionality decision are also being outlined there.

**Comment by m-branson** [comment]
@comzeradd @akatsoulas : the CoSS drive folder now contains [prototype assets](https://drive.google.com/open?id=0B0vmiicLLrGuVkNxMjVSbjZmYms).

**Comment by m-branson** [comment]
Visual design prototype (initial iteration) is complete! Closing issue & epic.
