### ISSUE TITLE
CoSS Sprint Goal 9 

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#165]
"As a user I want to become an Open Source Club Captain."
"As Club Captain, I want to be able to start a club. "
Front End Implied: Registration, Club Page, Edit 
Admin Implied: Registration Form, Landing Page

## Extend Functionality
**Theme:** _We are able to launch a Club site with basic navigation_
- [x] Registration form creation and integration with IAM and SF #156, #157 
- [ ] Dockerize Project #143 
- [x] Adjust Clubs landing page to the new UI #171
- [ ] Refactor single column layout #168 

### Maintenance
- [x] Use hashes in pip requirements #136
- [x] Use python-decouple in project's settings #133
- [x] code housekeeping #175

### Design
**Theme:** _Have a visually designed clickable prototype for Open Source Clubs_

[**Prototype Link**](https://invis.io/QNC0SQD24)
- [ ] **[UX/UI Epic]** Open Source Clubs: Visual Design #145 
- [x] Review Club Captain flow (#146), iterations needed?
- [x] Apply visual design to the Club Member flow #147 
- [x] Find A Group #163 
- [x] Rename design components > generalize for templating #166
- [x] Design > Dev Hand-off (What does Nikos need?)
- [ ] Migrate Prototype to Mozilla InVision #169 
- [x] Update Prototype UI Colors #170
- [x] Investigate Prototype Naming/Logo Placement #173 
- [x] Update Clubs logo to align with latest brand updates #174 
**[Stretch Goal]**
- [ ] User Menu #162
- [ ] About Page #160

### Deployment
- [ ] Deploy on ParSys AWS infrastructure (coss.staging.paas.mozilla.community, coss.mozilla.community) #155

**Comment by m-branson** [comment]
Updated Design goals to reflect sprint planning. 

Added tasks for **Review of #146** and **Design > Dev Hand-off needs identification**.

**Comment by m-branson** [comment]
Added #169, #170 and #173 to the design goal.

**Comment by m-branson** [comment]
Added [prototype link](https://invis.io/QNC0SQD24) to design section for quick reference.

**Comment by m-branson** [comment]
Added #174 to design goal.

**Comment by m-branson** [comment]
Edited naming of #163 to reflect strategic changes to navigation.
