### ISSUE TITLE
CoSS Sprint 10 Goal

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#189]
**"As a user I want to become an Open Source Club Captain."**
**"As a program manager, I want to be able to create a sign up form for leaders."**
Front End Implied: Registration, Acknowledgement page, Edit
Admin Implied: Registration Form, Landing Page

**Extend Functionality**
- [x] Acknowledgement page Implementation https://github.com/mozilla/coss/issues/192 - Nikos
- [x] Django form implementation https://github.com/mozilla/coss/issues/157 - Tasos
- [x] Dockerize project https://github.com/mozilla/coss/issues/143 - Nemo/Tasos
- [ ] Admin accessible registration form #197 - Tasos
- [x] STRETCH: Template for Entity page https://github.com/mozilla/coss/issues/193 - Nikos

**Design**
[Prototype Link](https://invis.io/QNC0SQD24)
[UX/UI Overview Doc](https://docs.google.com/a/mozilla.com/document/d/1IAtQlUtNU6yA8xJJkl1EyEiEnkXtNPl6QOLE_zzL9Gg/edit?usp=sharing)
[OS Clubs Prototype](https://invis.io/UYC9ST17F) (linked via main prototype)

- [x] New Member flow #188 
- [x] User Menu #162 
- [x] Find an Event #158
- [x] Event Detail Page Update (Splash Version) #190
- [x] Fix Prototype Navigation #199 
STRETCH: 
- [x] About #160 
- [x] Resources #161 
- [x] Log In/Sign Up Cross-linking #191 

**Splash**
- [x] Prep Splash Demo #194 
- [x] Submit RRA #195

**General**
- [ ] Roadmap #196

**Comment by m-branson** [comment]
Added #191 to design stretch goals.

**Comment by m-branson** [comment]
Added prototype link + link to UX/UI overview doc to Design section.

**Comment by m-branson** [comment]
Added #199 to design sprint goals.

**Comment by m-branson** [comment]
Added additional prototype information to sprint goal for posterity.
