### ISSUE TITLE
CoSS Sprint Goal 11

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#209]
- [x] CMS debrief and post prototype selection #206 
- [x] Infrastructure for post prototype CMS #205 
- [ ] Dockerize if needed #207 
- [ ] Documentation on set up #208 
- [ ] Set up alternative CMS and test against a set of criteria #212
- [ ] Finalize and publish Front End Job freelance description #210 
- [ ] Create Event Management next steps plan #211
