### ISSUE TITLE
CoSS Sprint goal 13

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#244]
## Content Management and Website Builder Utilities
- [x] site is live in production #245 
- [x] Static version of the landing page #251
- [ ] GA analytics working https://github.com/mozilla/parsys/issues/215
- [x] 1 page template #250
## Discussion Utility
- [ ] Discourse open category feed integration 
   * Acceptance Criteria: Integrate feed from public category with CoSS https://github.com/mozilla/discourse/issues/88
- [ ] Some sort of activity integration (member number, last post, etc)
   * Acceptance Criteria: Integrate metrics from private category with CoSS https://github.com/mozilla/discourse/issues/89
## Management
- [ ] 6 technical interview are completed, 3 cultural fit interviews
- [ ] Utility Impact Matrix is completed #238 
- [ ] Splash SOW is completed #249 item 1
