### ISSUE TITLE
CoSS Sprint 14 Goal

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#285]
- Multi-site approach validation
  - [x] Add a single page with a new domain name bd4aacdc9f6adbd54f41a4eb635503546db5ef84
  - [x] Share a component/utility between the two sites running in CoSS
  - [ ] Experiment and document how multi-site functionality works in Wagtail.
- Finish implementing Entity page template #290
  - [ ] UI changes
  - [ ] Dynamic fields exposed on admin interface
- Finish implementing Homepage page template #291
  - [x] UI changes
  - [x] Dynamic fields exposed on admin interface
- Add About & Category Landing templates
  - [x] Add About template 9f3358780af84684633b56158912c614f7e817bb
  - [x] Add Category Landing template
- Add FAQ page.
  - [x] Add FAQ page using StreamFields.
- Complete static list page with some dynamic fields.
- OS Clubs UX
  - [ ] Content Outline Review #286
  - [ ] Phase 1 Wireframe #278 
  - [ ] Activity Page UI Design #287 
  - [ ] Resources Page UI Design #288 
  - [ ] Homepage & Global UI Refinement #305
  - [ ] About Us UI Refinement #313
  - [ ] Discourse UI Integration #306
- Template Naming
  - [ ]  Prototype Template Renaming #289
- Screenshotted Discourse integration in `master`
  - [ ] Integrate public category feed https://github.com/mozilla/discourse/issues/88
  - [ ] Integrate metrics from private category https://github.com/mozilla/discourse/issues/89
  - [ ] Document plans for making editable from admin interface https://github.com/mozilla/discourse/issues/93
- Start QA work 
  - [ ] Familiarize with CoSS setup and admin account on stage #293 
  - [ ] Define at least 2 test cases for the current CoSS functionality  #294 
- Technical Debt
  - [x] Add CSP 3851677fefdff05c85fbfe13cc2f3403dfbb392b
  - [x] Update to Wagtail 1.12 5da4a219d10e32623e319f5da2381a6a621ed486

**Comment by m-branson** [comment]
Added #305, #313 and #306 to the UX goal.
