### ISSUE TITLE
CoSS Sprint Goal 15

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#351]
Continue work on Milestone 1 for OS Clubs - https://projects.invisionapp.com/share/AZDAP6MPT

Term alignment:
* Ready for QA: Dev, CSS complete
* Done: QA’ed using test content, ready for hand off to program staff

TODOs:
- [ ] FAQ Page Iteration 0 (undesigned) as done (content done, URL change to `/faq/`)
- [ ] FAQ Page Iteration 1 (designed version) as done
  - [x] Design #380
  - [ ] Dynamic template

- [ ] Content clarity 

- [x] About Page as done - #352 
- [x] Activity Page as done - #353, #347
- [x] Entity Page is ready-for-QA - #355, #349 
_Acceptance criteria - Dynamic fields where appropriate (image gallery, club capts)_  

- [x] Resources Page (static template) as done #387
_Acceptance criteria - Mentors float above guides list in responsiveness, admin controled unordered lists_

- [ ] Navigation as done - #354, #348 
_Acceptance criteria - reusable app available across CoSS sites, Dynamically generated, has elements that need to overridden for each site_

- [x] Phase 1 Prototype wrap up #322
- [x] OS Clubs Logo Update #356
- [x] UX/UI Design: US vs. International Dialog Page #357
- [x] UX/UI Design: US Pilot Program Static Banner (Old Site) #358
- [x] UX/UI Sketch file cleaning #359
