### ISSUE TITLE
CoSS Sprint Goal 16

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#456]
## Launch Support
- [ ] Answering questions as needed
- [ ] Resources page not in topbar #457 
- [ ] Different size in collaborator boxes #458 
- [ ] Bottom bar not present in landing page #459 
- [ ] Increase container width #460 
- [ ] Fix fonts inconsistencies #461 
- [ ] Fix link fonts and colors #462 

## Tech debt
- [ ] Staging = Production #466
- [ ] White labeling 
  - [ ] Make a component list
    - [ ] Identify component that is used in more then one page
    - [ ] Complete componentizing 
  - [ ] About page #381 
  - [ ] Social component #425 
  - [ ] Dynamic footer #258 
- [ ] Test Automation Plan
- [x] Automated updates for notifcations/dependencies #465 
- [ ] Jinja 2 support #232
- [ ] Use a StreamBlock #438 
- [ ] Switch to Google Tag Manager #434 

## UX
- [ ] Initiate Admin UX Assessment #500

## Management 
- [ ] Splash Contract
- [ ] Interviews
- [ ] Milestone Map

## Backlog
- [ ] Location Data Epic Issue (plan)
