### ISSUE TITLE
CoSS Sprint 17 Goal

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#513]
## Tech debt
- [ ] Staging = Production #466
- [ ] White labeling 
  - [ ] Make a component list
    - [ ] Identify component that is used in more then one page
    - [ ] Complete componentizing 
  - [ ] About page #381 
  - [ ] Social component #425 
  - [ ] Dynamic footer #258 
  - [ ] Content pages #529 
- [ ] Test Automation Plan
- [ ] Jinja 2 support #232
- [ ] Use a StreamBlock #438 
- [x] Switch to Google Tag Manager #434 
- [x] Add Mozilla logo in Wagtail's admin inteface #515 

## UX
- [ ] ~~Technical assessment and potential implementation of 'Dashboard' and "navigation of Wagtail  Admin from  UX Assessment document in #500 - needs ticket number~~
- [ ] Continued Admin UX Assessment #500 (Technical Assessment of UX recommendations has been added to the backlog #516)
- [x] OSSN Logo Update #517
