### ISSUE TITLE
Sprint 18 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla/coss#539]
## Sprint Goals
- [x] Finalize OSSN Logo Update #517
- [ ] Service technical debt #259 #529 #232 #446 #438
- [ ] Improve page speed / site experience #488
- [x] Create and size stories for Admin UX #516
- [ ] Get SplashThat credentials #249
- [ ] Miscellaneous #238 #406 #422
- [x] Empty the _Stakholder Acceptance_ column

**Comment by a-kilroy** [comment]
Great job @hmitsch ! Thanks again for covering for me.
