### ISSUE TITLE
Sprint 19 Goal

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#556]
## DRAFT Sprint Goals

- [ ] CoSS is ready for a new client (Potential client: challenges.mozilla.community) 
  - [ ] TD - Refactor Content pages #529
  - [ ] TD - StreamBlock #438
  - [ ] TD - Jinja2 Support #232
  - [x] Improve page speed / site experience - Image Resize #568
  - [ ] Reusable social media #425
  - [ ] Help text for WYSIWYG #404
  - [ ] Identify any outstanding questions for multi-site 

<hr>

- [ ] Edge Bugs
  - [x] Page content overlaps footer section #490
  - [ ] Expanded and reduced logo not displayed correctly #491

<hr>

- [ ] Miscellaneous
  - [ ] Evaluation matrix by utility #238 
  - [ ] Locking down tags #406
  - [ ] Mozillians/Coss Privacy Policy #422

<hr>

- [ ] Create and size stories for Admin UX round 2 #516
- [ ] Get understanding for Splash next steps

<hr>

- [ ] Admin UX round 1
  - [ ] Update Admin to reflect most recent branding - font, colors, logo #558
  - [x] Update "Sign in to Wagtail" to " Mozilla CoSS Website Utility" #559
  - [ ] Welcome Message updated to a message to a link to an onboarding doc #560
  - [ ] Create onboarding doc #561
  - [x] Remove user image in welcome banner #562
  - [ ] Change 'pages' in navigation to 'sites' #563
