### ISSUE TITLE
Implement the basic landing page for "network"

### ISSUE THREAD

**Issue by Pomax** [mozilla/coss#98]
This work uses the https://github.com/mozilla/coss/tree/mezzanine branch as main branch.

---

As dual-purpose work, the following comp should be implemented. Structurally it has high overlap with the CoSS minimal page, while styling etc. is a fluid notion, and can be adapted to yield either a CoSS or Network page.

![screenshot 158](https://cloud.githubusercontent.com/assets/177243/24256149/97f2b80c-0fa4-11e7-90c4-c62c61059be9.png)

### Subtasks

- [x] create a "network" app parallel to the cmstest app
  - the dir structure is a bit confusing here: the `coss` dir is our repository, the `./coss/cmstest` is the mezzanine project, with inside of that `./coss/cmstest/cmstest`, which is the actual test app. Django has the stupid quirk of creating a project dir and an app dir by the same name, so the top-level `cmstest` is the overarching Django project, and the inner `cmstest` is an actual app with files for admin/model/view/urls/etc. -- As such, we want a new app (`manage startapp network`) parallel to that inner `cmstest` so that we have `./coss/cmstest/cmstest` and a `./coss/cmstest/network` dirs.

- [x] set up a basic Django model that models the various dynamic parts of the above page
  - [x] specifically, model https://github.com/gvn/network/blob/f43710d77224604fa684474f402d669da6e63e9e/source/json/opportunities.json
- [x] create a base template skeleton for the above comp
  -  create a header template block
  -  create a footer template block
  -  create a page heading block
  -  create a 'free content' block
  -  create an optional "keep me updated" block
- [x] create styling for each block
  -  header
  -  footer
  -  page heading
  -  'free content'
  -  "keep me updated"

### ideally also

- [x] take a preexisting Django database, and see if it jives with a Mezzanine conversion
- [x] verify that Mezzanine and DRF, or a REST plugin to mezzanine, works, so we can query mezzanine as an API server, too, so that we can query the CMS as an API server.

### related issues

Network: https://github.com/mozilla/network-api/issues/59, https://github.com/mozilla/network-api/issues/61
CoSS: https://github.com/mozilla/coss/issues/40, https://github.com/mozilla/coss/issues/44, https://github.com/mozilla/coss/issues/68

### offloaded for now

- wrapping the Django model such that Mezzanine can work with, ideally preserving the original CMS-agnostic nature of the Django model

**Comment by alanmoo** [comment]
Putting this code into the Mezzanine branch when it happens. Or a branch off Mezzanine.

**Comment by alanmoo** [comment]
>* set up a basic Django model that models the various dynamic parts of the above page
>* wrap the Django model such that Mezzanine can work with, ideally preserving the original CMS-agnostic nature of the Django model

I'm struggling with the concept of writing a Django class that we then wrap in something else. I can trace my way down the `Page` class to find a `models.Model` eventually but I'm not sure I'm familiar enough with everything that's going on to construct the inheritance properly. @johngian maybe you can take a shot at it in the morning?

**Comment by Pomax** [comment]
Given multiple inheritance I would have thought the following might have worked:
```
class OurModel(models.Model):
  blah 
  more blah!

class MezzanineWrappedModel(OurModel, Page):
  code that bootstraps all fields from
  OurModel blindly for Mezzanine's Page
  class instead.
```

**Comment by cadecairos** [comment]
https://github.com/mozilla/coss/tree/mezzanine-networkapi

_mic drop_

**Comment by Pomax** [comment]
hooooooooooooooooooooooooooooooshi- nice one @cadecairos

**Comment by Pomax** [comment]
@johngian question - say I have a page called "My Event" built off of a page content-type `Event` on which we want to show "all issues that were built from the `Issues` model", so that you get a page like:
```
My Event

This event covers the following issues: Privacy.

For a quick summary explanation of our issues:
- Privacy: blahblah
- Inclusion: blahblah
```
Is it hacky, or is it actually proper Django use, to do the following:

```
# models.py

from ... import Issue

class Event(Page): 
  # ...
  def get_issues(self):
    return Issue.objects.all()
```
and then in the HTML template do:
```
{% for issue in page.event.get_issues() %}
  <div- {{ issue.name }}: {{ issue.description }}</div>
{% endfor}
```

**Comment by Pomax** [comment]
Initial stub attempt, https://github.com/mozilla/coss/pull/103

![screenshot 169](https://cloud.githubusercontent.com/assets/177243/24317898/73437958-10ba-11e7-9687-8cb73ef9f5d3.png)

Note that this uses "give me all `FootLink` objects" inside the page template to generate all the footer links, and the signup callout block is also a completely different model, referenced by Foreign Key. Things are actually quite nice here.

**Comment by Pomax** [comment]
landing page stub so far is up on http://mezzanine-cms-experiment.herokuapp.com/internet-health-report/ with more insight on the admin page for it, https://mezzanine-cms-experiment.herokuapp.com/admin/network/pagewithcallout/5/change/ 

@gvn I've created you a superuser account with username `gvn` and as password the last entry of the options on the moz phonebook landing page (starts with `Ed`).  Might be useful to change after logging in ( users → click yo'self) but as an experimental instance, not critical.

**Comment by a-kilroy** [comment]
Looking good!!!

**Comment by Pomax** [comment]
updated http://mezzanine-cms-experiment.herokuapp.com/internet-health-report, this is a close enough approximation that we can get back do doing the last bits of template chopping and making sure all the files live in a place where django/mezzanine are happy with them.

**Comment by gvn** [comment]
That's cool, but I'm a bit confused. Why are you rebuilding this page? 

It already has been built over in `network`, and now I'm just adding tokens to the generated HTML so that Mezzanine can inject content.

**Comment by simonwex** [comment]
Agreed, this seems like duplicated effort. Could you fill me in?

**Comment by Pomax** [comment]
because I needed a concrete prototype to figure out mezzanine modeling, so it looks like the page you already have, but using mezzanine to help us figure out how data models and templating works

**Comment by Pomax** [comment]
I'm going to consider this work done, as the lessons learned during this exercise can now be repeated here in CoSS for the pages designed by @kristinashu, and in the Network repo by @cadecairos with assistance.
